config/routes.rb
Rails.application.routes.draw do
  
  resources :tumors do
    collection do
      get 'contact'
      get 'help_page'
    end
  end
  
  root 'tumors#inicio'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/tumor.rb
class Tumor < ActiveRecord::Base
end

app/controllers/tumors_controller.rb
class TumorsController < ApplicationController
  before_action :set_tumor, only: [:show, :edit, :update, :destroy]
  include Clasificar
  # GET /tumors
  # GET /tumors.json

  def index
    @tumors = Tumor.all.paginate(:page => params[:page], :per_page => 5)  
  end

  # GET /tumors/1
  # GET /tumors/1.json
  def show
  end

  # GET /tumors/new
  def new
    @tumor = Tumor.new
  end

  # GET /tumors/1/edit
  def edit
  end

  def get_content_to_display
     #Place code here
     render :update do |page|
          page.replace_html "display_ajax", :partial => 'name-of-your-partial'
     end
  end

  
  # POST /tumors
  # POST /tumors.json
  def create
    tp = tumor_params
    tp[:tipo_tumor], ad, p = tipo(tp)
    if p == nil
      p=0
    end
    @tumor = Tumor.new(tp)
    respond_to do |format|
      if @tumor.save
        format.html { redirect_to @tumor, notice: 'Se registro con exito con tipo de tumor => '+tp[:tipo_tumor].capitalize+
                                                  '.<>Arbol de decision:<>'+
                                                  ad+'<>Con un grado de acierto de: '+
                                                  p.to_s+
                                                  ' y un porcentaje de acierto de 83.19%' }
        format.json { render :show, status: :created, location: @tumor }
      else
        format.html { render :new }
        format.json { render json: @tumor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tumors/1
  # PATCH/PUT /tumors/1.json
  def update
    tp = tumor_params
    tp[:tipo_tumor], ad, p = tipo(tp)
    if p == nil
      p=0
    end
    respond_to do |format|
      if @tumor.update(tp)
        format.html { redirect_to @tumor, notice: 'El registro fue actualizado con exito con tipo de tumor => '+tp[:tipo_tumor].capitalize+
                                                  '.<>Arbol de decision:<>'+
                                                  ad+'<>Con un grado de acierto de: '+
                                                  p.to_s+
                                                  ' y un porcentaje de acierto de 83.19%' }
        format.json { render :show, status: :ok, location: @tumor }
      else
        format.html { render :edit }
        format.json { render json: @tumor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tumors/1
  # DELETE /tumors/1.json
  def destroy
    @tumor.destroy
    respond_to do |format|
      format.html { redirect_to tumors_url, notice: 'El registro se elimino con exito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tumor
      @tumor = Tumor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tumor_params
      params.require(:tumor).permit(:edad, :genero, :tipo_histologico, :grado_tumor, :hueso, :medula_osea, :pulmon, :pleura, :peritoneum, :higado, :cerebro, :piel, :cuello, :supraclavicular, :axilar, :mediastino, :abdominal, :tipo_tumor, :name, :email)
    end
end

app/helpers/tumors_helper.rb
module TumorsHelper
end

app/views/tumors/contact.html.erb
<% content_for :titulo do %>
  Información de Contacto
<% end %>
<% content_for :tituloPanel do %>
  Información de Contacto
<% end %>

<h3>Datos Personales</h3><br>
<h4>Nombres:</h4><br>
<h5>Gabriel Cobeña Cedeño</h5><br>
<p>Estudiante de la Pontificia Universidad Catolica del Ecuador Sede Esmeraldas, el presente es un Trabajo Para la Materia de Aplicaciones Difusas.</p>

app/views/tumors/edit.html.erb
<% content_for :titulo do %>
  Editar Registro
<% end %>
<% content_for :tituloPanel do %>
  Editando Registro
<% end %>

<%= render 'form' %>

app/views/tumors/help_page.html.erb
<% content_for :titulo do %>
  Información de Terminos
<% end %>
<% content_for :tituloPanel do %>
  Información de Terminos
<% end %>

<h4>TIPO HISTOLÓGICO</h4>
<p>En la actualidad, está ampliamente aceptado que existen múltiples patrones morfológicos del carcinoma de mama y que el tipo histológico representa un factor pronóstico (5). Entre el 50% y el 70% de los carcinomas infiltrantes de mama son del tipo ductal sin características histológicas especiales (referido en la literatura anglosajona como ductal no special type, CDNST) (5). El resto de los casos corresponde a tipos histológicos definidos, algunos de los cuales deben ser destacados por su especial mejor pronóstico (33,34). Hay que tener en cuenta, que existe un grado de subjetividad a la hora de definir los tipos histológicos, por lo que la frecuencia relativa de los mismos varía según las series analizadas. Para que un tumor sea considerado como tipo histológico especial, las características que lo definen deben estar presentes al menos en el 90% de la masa tumoral; en caso de que estas características estén presentes en menor cuantía, mezcladas con áreas de CDNST, se denominan variedades de tipos especiales o formas mixtas.
Existen escasos estudios que hayan analizado la relación entre el tipo histológico del carcinoma infiltrante de mama y la supervivencia a largo plazo. En uno de ellos, se observó una cantidad relativa mayor de carcinomas tubulares, coloides, medulares y lobulillares infiltrantes en las pacientes con supervivencia superior a los 25 años, comparadas con las que sobrevivieron menos de 10 años (35). Estudios posteriores añadieron el papilar y cribiforme infiltrantes al grupo inicial (36).
</p>


<h4>¿QUE SON LOS GRADOS DE TUMOR?</h4>
	
<p>El grado de un tumor es la descripción de un tumor que se basa en la forma como se ven las células y el tejido de un tumor al microscopio. El grado de un tumor es una indicación de la rapidez con la que probablemente crecerá y se extenderá el tumor. Si las células del tumor y la organización del tejido del tumor se asemejan a las células y a los tejidos normales, el tumor se llama "bien diferenciado".  Estos tumores tienden a crecer y a extenderse a un paso más lento que los tumores que son "indiferenciados" o "escasamente diferenciados", los cuales tienen células que se ven anormales y a los que les pueden faltar las estructuras de tejido normal. Con base en estas y en otras diferencias de apariencia al microscopio, los médicos asignan un "grado" numérico a la mayoría de loscánceres. Los factores que se usan para determinar el grado de los tumores pueden variar entre los diferentes tipos de cáncer.
El grado del tumor no es lo mismo que el estadio de un cáncer. El estadio del cáncer se refiere al tamaño o a la extensión (etapa) del tumor original (primario) y a si las células cancerosas se han diseminado en el cuerpo.  El estadio del cáncer se basa en factores como el lugar del tumor primario, el tamaño del tumor, si están afectados los ganglios linfáticos regionales (la extensión del cáncer a los ganglios linfáticos cercanos), y al número de tumores presentes.  Hay más información disponible sobre la estadificación en la hoja informativa del NCI Estadificación del cáncer.
</p>
<h5>¿Cómo se clasifican los grados de un tumor?</h5>
<p>Los sistemas de gradación de los tumores difieren dependiendo del tipo de cáncer. En general, se asigna un grado de 1, 2, 3 o 4 a los tumores, dependiendo de qué tan anormalsean. En los tumores de grado 1, las células tumorales y la organización del tejido del tumor tienen una apariencia cercana a la normal. Estos tumores tienden a crecer y a diseminarse lentamente. Por el contrario, las células y el tejido de los tumores de grado 3 y 4 no se ven como las células y el tejido normales. Los tumores de grado 3 y 4 tienden a crecer rápidamente y a diseminarse con más rapidez que los tumores de un grado inferior.
Si no se especifica un sistema de gradación para un tipo de tumor, generalmente se usa el sistema siguiente (1):
</p>


<h4>PERITONEO</h4>
 
<p>
El peritoneo es la membrana que recubre todos los órganos del abdomen . Se compone de dos capas: una que recubre la cavidad abdominal y la otra que recubre los órganos. Entre ambas queda una cavidad virtual, normalmente vacía. El peritoneo es a menudo una localización secundaria de un cáncer, es decir, las células cancerosas provienen de otros órganos como elpáncreas, el estómago, el colon o el cáncer de ovario: hablamos en este caso de carcinomatosis peritoneal. Cuando el cáncer se desarrolla a partir de las células del propio peritoneo lo llamamoscáncer primitivo del peritoneo. Forma parte de los cánceres llamados mesoteliomas que también puede afectar a la pleura (membrama situada alrededor de los pulmones) o al pericardio(memebrana que recubre el corazón) . 
</p>
<h5>Síntomas</h5>
<p>
Diferentes síntomas pueden hacer sospechar un cáncer del peritoneo. En general, el descubrimiento se realiza ante síntomas como el dolor abdominal o el aumento de lacircunferencia abdominal en etapas avanzadas. Otras síntomas pueden ser problemas con eltránsito intestinal o la formación de una hernia. En algunos casos, por otra parte, podemos encontrar una mesotelioma antes de que sea responsable de síntomas. 
</p>
<h5>Diagnóstico</h5>
<p>
	El diagnóstico de cáncer peritoneal se suele hacer con un escáner abdominal. Para saber si se trata de un tumor primitivo (mesotelioma) o secundario a una carcinomatosis peritoneal el análisis del líquido peritoneal nos puede ayudar. Si se trata de una carcinomatosis peritoneal se debe buscar el cáncer primario involucrados. Si se trata de un mesotelioma se realizará un estudio de extensión, es decir, un conjunto de exámenes que permiten buscar si hay metástasis(localizaciones secundarias del cáncer). 
</p>




<h4>PLEURA</h4>
<p>
La pleura es una membrana torácica muy delgada pero muy sólida que se compone de dos capas o láminas separadas por un espacio vacío, la cavidad pleural. Las dos capas, por lo tanto, se pueden desplazar con facilidad una sobre la otra. La hoja denominada pleura visceral o pleura pulmonar cubre la cara externa de los pulmones, mientras que la hoja denominada pleura parietal cubre la pared interna de la caja torácica. 
<br>
La pleura permite proteger a los pulmones por reducir los golpes y bloquear el paso de ciertos virus y bacterias. En caso de presencia de líquido en la cavidad se llama pleuresía; y en caso de presencia de gas hablamos de neumotórax. 
Su función principal es facilitar los movimientos pulmonares. Las patologías que pueden afectarla son de tipo inflamatorio, tumoral, traumático y derrames de líquidos (hidrotórax, hemotórax, piotórax) o gaseosos (neumotórax).
</p>
<h4>MEDIASTINO</h4>
<p>
Los tumores mediastinales son masas o neoplasias que se forman en el mediastino, una zona en la mitad del tórax que separa los pulmones.
Causas
El mediastino es la parte del tórax que está entre el esternón y la columna vertebral y entre los pulmones. Esta zona contiene el corazón, los vasos sanguíneos grandes, la tráquea, el timo, el esófago y tejidos conectivos. El mediastino se divide en tres secciones:
<li>Anterior (frontal)</li>
<li>Media</li>
<li>Posterior (atrás)</li><br>
Los tumores del mediastino son infrecuentes.
La ubicación más común para los tumores del mediastino depende de la edad del paciente. En los niños, dichos tumores son más comunes en el mediastino posterior. Estos tumores con frecuencia comienzan en los nervios y no son cancerosos (benignos).
La mayoría de estos tumores en los adultos ocurre en el mediastino anterior y generalmente son linfomas, tumores de las células germinativas o timomas cancerosos (malignos). Estos tumores son más frecuentes en personas entre los 30 y los 50 años.
Síntomas
</p>
<h4>GANGLIO AXILAR</h4>
<p>
Un ganglio axilar es un ganglio linfático situado en la axila. Este pequeño cuerpo redondeado tiene un papel específico para transportar el líquido linfático o linfa. Esta participa en la defensa del cuerpo y proviene de los vasos linfáticos que drenan el brazo y que va a drenar al sistema de circulación sanguínea venosa. Muy pequeños, los ganglios axilares no se perciben generalmente en la palpación de las axilas, pero a veces pueden aparecer hinchados especialmente en caso de inflamación de una parte del brazo causado por un virus o una bacteria. Los ganglios linfáticos axilares también pueden aumentar su volumen en las mujeres con cáncer de mama. Diferentes exámenes, como un análisis de sangre en la etapa inicial, permiten encontrar las causas de esta inflamación.
</p>

<h4>SUPRACLAVICULAR</h4>
<p>
	La región supraclavicular, o triángulo supraclavicular, o hueco supraclavicular, está situada en las partes laterales del cuello, por encima de la clavícula, por detrás de la región esterno-cleido-mastoidea y por delante de la región de la nuca.
   Sus límites son: por delante el borde posterior del ECM, por detrás, el borde anterior del trapecio, por debajo la clavícula.
   Tiene forma triangular. La base o lado inferior es la clavícula, el vértice superior está formado por la unión del ECM y el trapecio. Por eso se llama también triángulo. Está ocupado en toda su extensión por una depresión cuya profundidad es muy variable, según los individuos, que aumenta normalmente de arriba abajo.
</p>

app/views/tumors/index.html.erb
<% content_for :titulo do %>
  Lista de Registro de Tumores
<% end %>
<% if notice.to_s != '' %>
  <div class="card-panel pink lighten-2">
    <%= notice %>
  </div>
<% end %>
  <h1>Lista de Registros</h1>
      <table class="responsive-table">
        <thead>
          <tr>
            <th>Edad</th>
            <th>Genero</th>
            <th>Tipo histologico</th>
            <th>Grado tumor</th>
            <th>Tipo tumor</th>
            <th>Expandir Elementos</th>
            <th>Editar Elementos</th>
            <th>Eliminar Elementos</th>
          </tr>
        </thead>

        <tbody>
          <% @tumors.each do |tumor| %>
            <tr>
              <td>
                <% if tumor.edad %>
                  <% if tumor.edad == ">30" %>
                    <%= "Menor a 30" %>
                  <% elsif tumor.edad = "30-59" %>
                    <%= "De 30 a 59" %>
                  <% elsif tumor.edad =="<60" %>
                    <%= "Mayor a 60" %>
                  <% end %>
                <% else %>
                  <%= "No se especifico la edad" %>
                <% end %>
              </td>
              <td>
                <% if tumor.genero %>
                  <% if tumor.genero == "hombre" %>
                    <%= "Masculino" %>
                  <% elsif tumor.genero = "mujer" %>
                    <%= "Femenino" %>
                  <% end %> 
                <% else %>
                  <%= "No se especifico un genero" %>
                <% end %>
              </td>
              <td><%= tumor.tipo_histologico.capitalize %></td>
              <td><%= tumor.grado_tumor.capitalize %></td>
              <td><%= tumor.tipo_tumor.capitalize %></td>
              <td><%= link_to 'Mostrar Todo', tumor, :class => "actions btn waves-effect waves-light col s3 blue center-align white-text " %></td>
              <td><%= link_to 'Editar', edit_tumor_path(tumor), :class => "actions btn waves-effect waves-light col s3 green center-align white-text " %></td>
              <td><%= link_to 'Eliminar', tumor, method: :delete, data: { confirm: '¿Está seguro de querer eliminar el registro?' },
                    :class => "actions btn waves-effect waves-light col s3 pink center-align white-text " %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

<br>
<ul class="pagination">
<%= will_paginate @tumors, previous_label: "<li class='disabled'><i class='material-icons'>chevron_left</i>Anterior</li>", next_label: "<li>Siguiente<i class='material-icons'>chevron_right</i></li>", :class => "waves-effect", current: "asd" %>
</ul>

app/views/tumors/inicio.html.erb
  <br><br>
  <div class="slider">
    <ul class="slides">
      <li>
        <img src="http://www.meedicina.com/wp-content/uploads/2015/07/Medicina-personalizada.jpg"> <!-- random image -->
        <div class="caption center-align">
          <b><h3 class="black-text">Informatica en el Campo Medicinal!</h3></b>
          <h5 class="light black-text">Integración de sistemas expertos en la medicina.</h5>
        </div>

      </li>
      <li>
        <img src="https://lh3.googleusercontent.com/-l76yFH2kGxc/TYn8CzNe4vI/AAAAAAAAABU/QYzETcjZOG0/s1600/arq.bmp"> <!-- random image -->
        <div class="caption materialboxed left-align">
          <b><h3 class="black-text">Diagrama del funcionamiento de sistemas expertos!</h3></b>
        </div>
      </li>
      <li>
        <img src="http://blauveterinaris.com/es/wp-content/uploads/2014/11/tumores.jpg"> <!-- random image -->
        <div class="caption right-align">
          <b><h3 class="black-text">Tumores!</h3></b>
          <h5 class="light black-text">Deformación de células lo que permite la aparicion de tumores</h5>
        </div>
      </li>
    </ul>
  </div>

<h3>Tumor Primario</h3>
<p>
  Un tumor es cualquier alteración de los tejidos que produzca un aumento de volumen. Es un agrandamiento anormal de una parte del cuerpo que aparece, por lo tanto, hinchada o distendida. El tumor, junto con el rubor, el dolor y el calor, forman la tétrada clásica de los síntomas y signos de la inflamación.
En sentido restringido, un tumor es cualquier masa o bulto que se deba a un aumento en el número de células que lo componen.Si este crecimiento celular tiene su origen en diversas células (policlonal) hablamos de hiperplasia y si se trata de una neoformación celular que tiene su origen en una única célula (monoclonal) la llamamos neoplasia independientemente de que sean de carácter benigno o maligno en funcion de su capacidad ó no de infiltrar los tejidos que le rodean. Cuando un tumor es maligno tiene capacidad de invasión o infiltración y de producir metástasis a lugares distantes del tumor primario, siendo un cáncer metastásico.
</p>
<h3>Sistema Experto</h3>
<p>
  Es una aplicación informática capaz de solucionar un conjunto de problemas que exigen un gran conocimiento sobre un determinado tema. Un sistema experto es un conjunto de programas que, sobre una base de conocimientos, posee información de uno o más expertos en un área específica. Se puede entender como una rama de la inteligencia artificial, donde el poder de resolución de un problema en un programa de computadora viene del conocimiento de un dominio específico. Estos sistemas imitan las actividades de un humano para resolver problemas de distinta índole (no necesariamente tiene que ser de inteligencia artificial). También se dice que un SE se basa en el conocimiento declarativo (hechos sobre objetos, situaciones) y el conocimiento de control (información sobre el seguimiento de una acción).
</p>

app/views/tumors/new.html.erb
<% content_for :titulo do %>
  Nuevo Registro
<% end %>
<% content_for :tituloPanel do %>
  Nuevo Registro
<% end %>

<%= render 'form' %>

app/views/tumors/show.html.erb
<% content_for :titulo do %>
  Historia Clinica
<% end %>
<% content_for :tituloPanel do %>
  Registro Completo
<% end 
    if notice.to_s != ""
%>

<div class="card-panel teal lighten-2">
  <% 
    asd = notice.split(/<>/) 
    asd.each do |item|
  %>
  <%= item %> <br>
  <% end %>
</div>
<% end %>
<div class="row">
  <p>
    <div class="input-field col s3 center-align">
      <b>Nombre:</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.name %>
    </div>
  </p>

  <p>
    <div class="input-field col s3 center-align">
      <b>Email:</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.email %>
    </div>
  </p>
</div>


<div class="row">
  <p>
    <div class="input-field col s3 center-align">
      <b>Edad:</b>
    </div>
    <div class="input-field col s3 center-align">
                <% if @tumor.edad %>
                  <% if @tumor.edad == ">30" %>
                    <%= "Menor a 30" %>
                  <% elsif @tumor.edad = "30-59" %>
                    <%= "De 30 a 59" %>
                  <% elsif @tumor.edad =="<60" %>
                    <%= "Mayor a 60" %>
                  <% end %>
                <% else %>
                  <%= "No se especifico la edad" %>
                <% end %>
    </div>
  </p>

  <p>
    <div class="input-field col s3 center-align">
      <b>Género:</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.genero.capitalize %>
    </div>
  </p>
</div>

<div class="row">
  <p>
    <div class="input-field col s3 center-align">
      <b>Tipo Histológico:</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.tipo_histologico.capitalize %>
    </div>
  </p>

  <p>
    <div class="input-field col s3 center-align">
      <b>Grado Tumor:</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.grado_tumor.capitalize %>
    </div>
  </p>
</div>

<div class="row">
  <p>
    <div class="input-field col s3 center-align">
      <b>Dolor a los Huesos:</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.hueso %>
    </div>
  </p>

  <p>
    <div class="input-field col s3 center-align">
      <b>Medula Osea:</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.medula_osea %>
    </div>
  </p>
</div>

<div class="row">
  <p>
    <div class="input-field col s3 center-align">
      <b>Problemas en los pulmones:</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.pulmon %>
    </div>
  </p>

  <p>
    <div class="input-field col s3 center-align">
      <b>Pleura:</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.pleura %>
    </div>
  </p>
</div>

<div class="row">
  <p>
    <div class="input-field col s3 center-align">
      <b>Peritoneo:</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.peritoneum %>
    </div>
  </p>

  <p>
    <div class="input-field col s3 center-align">
      <b>Problemas al Hígado:</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.higado %>
    </div>
  </p>
</div>

<div class="row">
  <p>
    <div class="input-field col s3 center-align">
      <b>Dolor de cabeza (cerebro):</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.cerebro %>
    </div>
  </p>

  <p>
    <div class="input-field col s3 center-align">
      <b>Problemas en la piel:</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.piel %>
    </div>
  </p>
</div>

<div class="row">
  <p>
    <div class="input-field col s3 center-align">
      <b>Dolor cuello:</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.cuello %>
    </div>
  </p>

  <p>
    <div class="input-field col s3 center-align">
      <b>Dolor al corazón (supraclavicular):</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.supraclavicular %>
    </div>
  </p>
</div>

<div class="row">
  <p>
    <div class="input-field col s3 center-align">
      <b>Problemas del ganglio axilar:</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.axilar %>
    </div>
  </p>

  <p>
    <div class="input-field col s3 center-align">
      <b>Dolor al pecho (mediastino):</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.mediastino %>
    </div>
  </p>
</div>

<div class="row">
  <p>
    <div class="input-field col s3 center-align">
      <b>Dolor abdominal:</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.abdominal %>
    </div>
  </p>

  <p>
    <div class="input-field col s3 center-align">
      <b>Tipo de tumor:</b>
    </div>
    <div class="input-field col s3 center-align">
      <%= @tumor.tipo_tumor.capitalize %>
    </div>
  </p>
</div>
<br>
<div class="row">
   <div class="input-field col s2"></div>
   <div>
     <%= link_to 'Edtar', edit_tumor_path(@tumor), :class => "actions btn waves-effect waves-light col s3 center-align white-text " %>
   </div>
   <div class="input-field col s2"></div>
   <div>
     <%= link_to 'Regresar', tumors_path, :class => "actions btn waves-effect waves-light col s3 pink center-align white-text " %>    
   </div>
  <div class="input-field col s2"></div>
</div>
</div>