config/routes.rb
Rails.application.routes.draw do
  
  resources :tumors do
    collection do
      get 'contact'
      get 'help_page'
    end
  end
  
  root 'tumors#inicio'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.erb
        <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col s12 center">
                  <div class="wow shake" data-wow-delay="0.4s">
                    <a class="btn-floating btn-large waves-effect waves-light red" href="#top"><i class="material-icons">expand_less</i></a>
                  </div>
              </div>
            </div>
          </div>
          <div class="footer-copyright center">
            <div class="container">
            © Copyright 2015. Todos los derechos reservados. Diseñado por <a href="http://wwww.facebook.com/gancoce" ><span class="light-green-text lighten-5
"><b>Gabriel Cobeña</b></span></a>
            </div>
          </div>
        </footer>

app/views/layouts/_navbar.html.erb
<div id="nav"> 
  <div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper container">
      <a href="#!" target="_blank" class="brand-logo">Tumor Primario</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to "Inicio", root_path, :class => "head-link" %></li>
        <li><%= link_to "Registrar", new_tumor_path %></li>
        <li><%= link_to "Listar", tumors_path %></li>
        <li><%= link_to "Información", help_page_tumors_path %></li>
        <li><%= link_to "Contacto", contact_tumors_path %></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><%= link_to "Inicio", root_path %></li>
        <li><%= link_to "Registrar", new_tumor_path %></li>
        <li><%= link_to "Listar", tumors_path %></li>
        <li><%= link_to "Información", help_page_tumors_path %></li>
        <li><%= link_to "Contacto", contact_tumors_path %></li>
      </ul>
    </div>
  </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
  	<% if content_for?(:titulo) %>
  		<%= yield(:titulo) %>
  	<% else %>
  		Tumor Primario
  	<% end %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="icon" type="image/jpg" href="../../assets/images/icon.jpg">  
  <link href='https://fonts.googleapis.com/css?family=Nunito:400,700' rel='stylesheet' type='text/css'>
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
    
    <%= render "layouts/navbar" %>
	<br/>
    <div class="container">
	    <div class="panel panel-danger">
	  		<div class="panel-heading">
		  		<h4>  	
		  			<% if content_for?(:tituloPanel) %>
				  		<%= yield(:tituloPanel) %>
				  	<% else %>
				  		Tumor Primario
				  	<% end %>
			  	</h4>
  			</div>
	  		<div class="panel-body">	    
	            <%= yield %>
	  		</div>
		</div>
    </div>
	
	<%= render "layouts/footer" %>

	<script>
		$(document).ready(function() {
	    	$('select').material_select();

	    	$(".dropdown-button").dropdown();
	    	$(".button-collapse").sideNav();
	    	new WOW().init();
	    	
	    	$("a[href='#top']").click(function() {
			  $("html, body").animate({ scrollTop: 0 }, "slow");
			  return false;
			});

			$('.collapsible').collapsible();
		    $('.slider').slider();
		    $('.materialboxed').materialbox();
		    $('.modal-trigger').leanModal();
		});
	</script>
	
</body>
</html>